version: '3'
services:
    # credentials guest:guest
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - '15672:15672'
            - '5672:5672'
networks:
    default:
        external:
            name: kafkanet