kind: Deployment
apiVersion: apps/v1
metadata:
  name: rmq-kconnect
  namespace: rmq
  selfLink: /apis/apps/v1/namespaces/rmq/deployments/rmq-kconnect
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmq-kconnect
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rmq-kconnect
    spec:
      containers:
        - name: rmq-kconnect
          image: ibmcase/rmqconnect
          ports:
            - containerPort: 8083
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
